Fixed warnings when running rubocop locally
.rubocop-https---raw-githubusercontent-com-devforce-dotfiles-master-rubocop-rubocop-trailhead-yml:72: `Layout/SpaceInsideHashLiteralBraces` is concealed by line 176
.rubocop-https---raw-githubusercontent-com-devforce-dotfiles-master-rubocop-rubocop-trailhead-yml:63: `Style/TrailingCommaInArrayLiteral` is concealed by line 182
.rubocop-https---raw-githubusercontent-com-devforce-dotfiles-master-rubocop-rubocop-trailhead-yml:66: `Style/TrailingCommaInHashLiteral` is concealed by line 186
.rubocop-https---raw-githubusercontent-com-devforce-dotfiles-master-rubocop-rubocop-trailhead-yml: Metrics/LineLength has the wrong namespace - should be Layout
.rubocop-https---raw-githubusercontent-com-devforce-dotfiles-master-rubocop-rubocop-trailhead-yml: Rails/FilePath has the wrong namespace - should be RSpec
Error: The `Layout/AlignParameters` cop has been renamed to `Layout/ParameterAlignment`.
(obsolete configuration found in .rubocop-https---raw-githubusercontent-com-devforce-dotfiles-master-rubocop-rubocop-trailhead-yml, please update it)
The `Layout/IndentFirstArrayElement` cop has been renamed to `Layout/FirstArrayElementIndentation`.
(obsolete configuration found in .rubocop-https---raw-githubusercontent-com-devforce-dotfiles-master-rubocop-rubocop-trailhead-yml, please update it)
The `Layout/IndentFirstHashElement` cop has been renamed to `Layout/FirstHashElementIndentation`.
(obsolete configuration found in .rubocop-https---raw-githubusercontent-com-devforce-dotfiles-master-rubocop-rubocop-trailhead-yml, please update it)
The `Style/BracesAroundHashParameters` cop has been removed.
(obsolete configuration found in .rubocop-https---raw-githubusercontent-com-devforce-dotfiles-master-rubocop-rubocop-trailhead-yml, please update it)